name: Web Sample

on: [push]

jobs:
  build:
    runs-on: macos-latest     
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.0.0'
        channel: 'stable'
    - name: Flutter Doctor
      run: flutter doctor
      working-directory: ./
    - name: Upgrades flutter
      run: flutter upgrade
      working-directory: ./
    - name: Enable Web
      run: flutter config --enable-web
      working-directory: ./example
    - name: Install dependencies
      run: flutter packages get
      working-directory: ./
#     - name: Setup tmate session
#       uses: mxschmitt/action-tmate@v3
#       timeout-minutes: 15
#     - name: Install dependencies
#       run: |
#         flutter clean
#         flutter pub upgrade
#       working-directory: ./
    - name: Build Web
      run: flutter build web
      working-directory: ./example
    - name: Deploy
      run: |
        cd ./example/build/web
        git init
        git config user.name  "CI"
        git config user.email "flutter-ci@github.com"
        git remote add secure-origin https://${{ secrets.ACCESS_TOKEN }}@github.com/maxim-saplin/data_table_2.git
        git checkout -b gh-pages
        git add .
        git commit -m "Updated dikt"
        git push --force secure-origin gh-pages
