name: Web Sample

on: [workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest     
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
 #       flutter-version: '2.0.5'
        channel: 'stable'
    - name: Flutter Doctor
      run: flutter doctor
      working-directory: ./
    - name: Upgrades flutter
      run: flutter upgrade
      working-directory: ./
    - name: Enable Web
      run: flutter config --enable-web
      working-directory: ./example
    - name: Install dependencies
      run: flutter packages get
      working-directory: ./
#     - name: Setup tmate session
#       uses: mxschmitt/action-tmate@v3
#       timeout-minutes: 15
#     - name: Install dependencies
#       run: |
#         flutter clean
#         flutter pub upgrade
#       working-directory: ./
    - name: Build Web
      run: flutter build web
      working-directory: ./example
    
    - name: Deploy ðŸš€
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: ./example/build/web
